fixtures:
  forge_modules:
    apache:
      repo: "puppetlabs/apache"
      ref:  "1.4.0"
    concat:
      repo: "puppetlabs/concat"
      ref:  "1.2.1"
    stdlib:
      repo: "puppetlabs/stdlib"
      ref:  "4.6.0"
    apt:
      repo: "puppetlabs/apt"
      ref:  "2.0.0"
    inifile:
      repo: "puppetlabs/inifile"
      ref:  "1.2.0"
    postgresql:
      repo: "puppetlabs/postgresql"
      ref:  "4.3.0"
    puppetdb:
      repo: "puppetlabs/puppetdb"
      ref:  "4.2.1"
  symlinks:
    puppet: "#{source_dir}"
