---
language: ruby
bundler_args: --without development
before_install: rm Gemfile.lock || true
sudo: false
rvm:
  - 1.9
  - 2.0
  - 2.1
script: "bundle exec rake test"
env:
  - PUPPET_VERSION="~> 3.6.0"
  - PUPPET_VERSION="~> 3.7.0"
  - PUPPET_VERSION="~> 3.7.0" PARSER="future"
  - PUPPET_VERSION="~> 4.0.0"
matrix:
  fast_finish: true
  include:
    - rvm: 1.9
      env: PUPPET_VERSION="~> 3.6.0"
    - rvm: 1.9
      env: PUPPET_VERSION="~> 3.7.0"
    - rvm: 2.0
      env: PUPPET_VERSION="~> 3.6.0"
    - rvm: 2.0
      env: PUPPET_VERSION="~> 3.7.0"
  exclude:
    - rvm: 1.9
      env: PUPPET_VERSION="~> 3.7.0" PARSER="future"
    - rvm: 1.9
      env: PUPPET_VERSION="~> 4.0.0"
    - rvm: 2.0
      env: PUPPET_VERSION="~> 4.0.0"
  allow_failures:
    - rvm: 2.0
      env: PUPPET_VERSION="~> 3.7.0" PARSER="future"
    - rvm: 2.1
      env: PUPPET_VERSION="~> 3.7.0" PARSER="future"
    - rvm: 2.1
      env: PUPPET_VERSION="~> 4.0.0"
notifications:
  email: true
