---
language: ruby
bundler_args: --without development
script: "bundle exec rake test"
rvm:
  - 1.8.7
  - 1.9.3
  - 2.0.0
  - 2.1.0
env:
  - PUPPET_VERSION="~> 3.6.0"
  - PUPPET_VERSION="~> 3.7.0"
#  - PUPPET_VERSION="~> 3.6.0" PARSER="future"
#  - PUPPET_VERSION="~> 3.7.0" PARSER="future"
notifications:
  email: true
